#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from gpu_profiles import GpuBuildProfile, resolve_gpu_profile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_PATH = ROOT / ".env"

BEGIN_MARKER = "# BEGIN SENTINELOS GENERATED GPU CONFIG"
END_MARKER = "# END SENTINELOS GENERATED GPU CONFIG"

SERVICE_PREFIXES = ("INFERENCE_", "LAE_DINO_", "MMROTATE_", "LSKNET_", "SAM2_")


@dataclass(frozen=True)
class HostGpu:
    name: str
    memory_total_mb: int
    memory_free_mb: int


@dataclass(frozen=True)
class HostGpuInfo:
    driver_version: str
    cuda_version: str
    gpus: tuple[HostGpu, ...]


def parse_version(value: str) -> tuple[int, ...]:
    parts = re.findall(r"\d+", value or "")
    return tuple(int(part) for part in parts)


def version_at_least(actual: str, minimum: str) -> bool:
    actual_parts = parse_version(actual)
    minimum_parts = parse_version(minimum)
    width = max(len(actual_parts), len(minimum_parts))
    return actual_parts + (0,) * (width - len(actual_parts)) >= minimum_parts + (0,) * (width - len(minimum_parts))


def parse_nvidia_smi_header(output: str) -> tuple[str, str]:
    driver_match = re.search(r"Driver Version:\s*([0-9.]+)", output)
    cuda_match = re.search(r"CUDA Version:\s*([0-9.]+)", output)
    if not driver_match:
        raise RuntimeError("Could not parse NVIDIA driver version from nvidia-smi output.")
    return driver_match.group(1), cuda_match.group(1) if cuda_match else "unknown"


def parse_gpu_query(output: str) -> tuple[HostGpu, ...]:
    gpus: list[HostGpu] = []
    for line in output.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = [part.strip() for part in line.split(",")]
        if len(parts) != 3:
            raise RuntimeError(f"Unexpected nvidia-smi GPU query row: {line!r}")
        name, total, free = parts
        gpus.append(HostGpu(name=name, memory_total_mb=int(float(total)), memory_free_mb=int(float(free))))
    if not gpus:
        raise RuntimeError("nvidia-smi did not report any GPUs.")
    return tuple(gpus)


def detect_host_gpu_info() -> HostGpuInfo:
    try:
        header = subprocess.run(
            ["nvidia-smi"],
            check=True,
            text=True,
            capture_output=True,
        ).stdout
        query = subprocess.run(
            [
                "nvidia-smi",
                "--query-gpu=name,memory.total,memory.free",
                "--format=csv,noheader,nounits",
            ],
            check=True,
            text=True,
            capture_output=True,
        ).stdout
    except FileNotFoundError as exc:
        raise RuntimeError("nvidia-smi was not found. Install NVIDIA drivers/tooling before configuring GPU builds.") from exc
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"nvidia-smi failed: {exc.stderr or exc.stdout}") from exc

    driver_version, cuda_version = parse_nvidia_smi_header(header)
    return HostGpuInfo(
        driver_version=driver_version,
        cuda_version=cuda_version,
        gpus=parse_gpu_query(query),
    )


def validate_driver(profile: GpuBuildProfile, driver_version: str) -> None:
    if not version_at_least(driver_version, profile.min_driver_version):
        raise RuntimeError(
            f"Host NVIDIA driver {driver_version} is too old for profile {profile.name} "
            f"(CUDA image {profile.cuda_version}); requires >= {profile.min_driver_version}. "
            "Update the host driver or use a lower CUDA/PyTorch profile."
        )


def generated_env_values(info: HostGpuInfo) -> dict[str, str]:
    primary_gpu = info.gpus[0]
    profile = resolve_gpu_profile(primary_gpu.name)
    validate_driver(profile, info.driver_version)

    values = {
        "GPU_MODEL": primary_gpu.name,
        "GPU_DRIVER_VERSION": info.driver_version,
        "GPU_CUDA_VERSION": info.cuda_version,
        "GPU_COUNT": str(len(info.gpus)),
        "GPU_MEMORY_TOTAL_MB": str(primary_gpu.memory_total_mb),
        "GPU_MEMORY_FREE_MB": str(primary_gpu.memory_free_mb),
        "NVIDIA_VISIBLE_DEVICES": "all",
        "NVIDIA_DRIVER_CAPABILITIES": "compute,utility",
    }

    for prefix in SERVICE_PREFIXES:
        values.update(profile.build_env(prefix))
        values[f"{prefix}GPU_PROFILE"] = profile.name

    return values


def render_generated_block(values: dict[str, str]) -> str:
    lines = [
        BEGIN_MARKER,
        "# Generated by python scripts/configure_host.py. Do not edit this block by hand.",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_generated_block(existing: str, block: str) -> str:
    generated_keys = {
        line.split("=", 1)[0]
        for line in block.splitlines()
        if line and not line.startswith("#") and "=" in line
    }
    pattern = re.compile(
        rf"(?:^|\n){re.escape(BEGIN_MARKER)}\n.*?\n{re.escape(END_MARKER)}(?:\n|$)",
        re.DOTALL,
    )
    without_block = pattern.sub("\n", existing)
    preserved_lines = []
    for line in without_block.splitlines():
        key = line.split("=", 1)[0].strip() if "=" in line else ""
        if key in generated_keys:
            continue
        preserved_lines.append(line)
    stripped = "\n".join(preserved_lines).rstrip()
    if pattern.search(existing):
        return (stripped + "\n\n" + block).strip() + "\n"
    if stripped:
        return stripped + "\n\n" + block + "\n"
    return block + "\n"


def configure_env_file(env_path: Path, info: HostGpuInfo) -> dict[str, str]:
    values = generated_env_values(info)
    existing = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
    env_path.write_text(replace_generated_block(existing, render_generated_block(values)), encoding="utf-8")
    return values


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Detect host GPU/driver and write SentinelOS Docker build settings to .env.")
    parser.add_argument("--env-file", type=Path, default=DEFAULT_ENV_PATH, help="Path to .env to update.")
    parser.add_argument("--dry-run", action="store_true", help="Print generated settings without writing .env.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    info = detect_host_gpu_info()
    values = generated_env_values(info)
    block = render_generated_block(values)
    if args.dry_run:
        print(block)
        return 0

    existing = args.env_file.read_text(encoding="utf-8") if args.env_file.exists() else ""
    args.env_file.write_text(replace_generated_block(existing, block), encoding="utf-8")
    print(
        f"Wrote GPU config for {values['GPU_MODEL']} "
        f"({values['INFERENCE_GPU_PROFILE']}, driver {values['GPU_DRIVER_VERSION']}) to {args.env_file}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
